
# the files are located: C:\Users\he227319\OneDrive - WA Health\1 _HMB\VIP collection for Syntax code or project titles\R codes\My_website

project:
  type: website
  output-dir: docs

website:
  title: "H. Mellie B"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "CV"
        file: CV.qmd
    right:
      - file: about.qmd
      - icon: github # gives icon
        text: GitHub # name of the icon
        href: https://github.com/ # icon link
        target: _blank # opens the link in the new tab
      - icon: twitter
        text: Twitter
        href: https://twitter.com
        target: _blank
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/dr-habtamu-mellie-bizuayehu-94285980/
        target: _blank
      - icon: envelope
        text: Email
        href: mailto:hmba2003@gmail.com
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    include-before-body: logo.Rhtml  # Link to the Rhtml file here

editor: visual




